### ISSUE TITLE
How can we review your change?

### ISSUE THREAD

**Issue by hkim15** [jeehoonkang/hafnium#5]
@jeehoonkang  - How can we review your change? Do you want to submit PR instead of directly pushing to the Git repo?

**Comment by jeehoonkang** [comment]
Thank you for suggesting code review for me!

I'd like to ask if I can experiment with the `hfo2` branch a little bit longer before starting code review.  I at least want to port a few important modules before preparing a reviewable code.  For the current time being, the `hfo2` branch is not quite reviewable due to its lack of proper comments, though I tried to make each commit as cohesive and relevant as possible.

Also pinging @wedsonaf :)  Hi!
